### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [ndw/comp.fonts#1]
What is the license of this project? :)

**Comment by ndw** [comment]
Good question. Some totally open one. Suggestions welcome.

**Comment by davelab6** [comment]
CC-BY-SA is what Wikipedia uses, I personally think its the best for this kind of thing. 

However, has the FAQ been solely authored by you? If not, maybe it will be necessary to track down all authors, or rewrite their parts.

**Comment by ndw** [comment]
I believe I got explicit permission to include all of the stuff I didn't write. It's been online for more than twenty years and no one's complained. I'll go with CC-BY-SA.
